name: "sb3_sac"
lr: 3e-4
buffer_size: 1000000
batch_size: 256
gamma: 0.99
tau: 0.005
alpha: 0.2
automatic_entropy_tuning: true
target_update_interval: 1
train_freq: 1
total_timesteps: 2000000
num_envs: 8
